import { PredefinedTemplate } from '../types/table';

export const ACH_COLORS = {
  blue: '#005FB6',
  green: '#52AE32',
  orange: '#EE7203',
  gray: '#707070',
  darkBlue: '#003E7E',
  lightBlue: '#E8F2FC',
  lightGreen: '#EFF9EB',
  lightOrange: '#FEF4EA',
  lightGray: '#F5F5F5',
  border: '#D0D7DE',
};

export const PREDEFINED_TEMPLATES: PredefinedTemplate[] = [
  {
    id: 'matriz-cari-san-oficial',
    name: '1. Matriz de Categorías SAN/CARI (Oficial ACH)',
    description: 'Matriz oficial de Severidad CARI con bloques cromáticos verde (#8DC63F), amarillo (#FFEE00), naranja (#F58220) y rojo (#ED1C24).',
    category: 'Seguridad Alimentaria',
    data: {
      title: 'Categorías SAN / Matriz de Afrontamiento y Severidad CARI',
      subtitle: 'Clasificación de Hogares según Consumo, Vulnerabilidad Económica y Agotamiento de Activos',
      headers: [
        'Dominio',
        'Indicador',
        'Seguridad Alimentaria (1)',
        'Seguridad Alimentaria Marginal (2)',
        'Inseguridad Alimentaria Moderada (3)',
        'Inseguridad Alimentaria Severa (4)',
      ],
      headerBgColors: [
        '#A6A6A6', // Dominio gris
        '#A6A6A6', // Indicador gris
        '#8DC63F', // Verde
        '#FFF200', // Amarillo
        '#F7941D', // Naranja
        '#ED1C24', // Rojo
      ],
      notes: '*Propuesta de escala ajustada de CARI para análisis territorial ACH.',
      source: 'Metodología CARI - Acción contra el Hambre Centroamérica',
      suggestedChartType: 'stackedBar',
      chartLabelCol: 0,
      chartValueCols: [2, 3, 4, 5],
      tableStylePreset: 'cari-severity',
      highlightStyle: 'soft-pastel',
      rows: [
        {
          id: 'cari-row-1',
          cells: [
            {
              id: 'c1-1',
              value: 'Consumo de alimentos',
              align: 'left',
              bgColor: '#D9D9D9',
              textColor: '#000000',
              isBold: true,
            },
            {
              id: 'c1-2',
              value: 'Puntaje de Consumo de alimentos - PCA',
              align: 'left',
              bgColor: '#EBF1F5',
              textColor: '#1E293B',
            },
            {
              id: 'c1-3',
              value: 'Aceptable / rCSI < 4',
              align: 'center',
              badgeColor: 'green',
              bgColor: '#F2F8EC',
            },
            {
              id: 'c1-4',
              value: 'Marginalmente Aceptable / rCSI > 4',
              align: 'center',
              badgeColor: 'yellow',
              bgColor: '#FFFDE6',
            },
            {
              id: 'c1-5',
              value: 'Limítrofe',
              align: 'center',
              badgeColor: 'orange',
              bgColor: '#FEF4EA',
            },
            {
              id: 'c1-6',
              value: 'Pobre',
              align: 'center',
              badgeColor: 'red',
              bgColor: '#FDECEC',
            },
          ],
        },
        {
          id: 'cari-row-2',
          cells: [
            {
              id: 'c2-1',
              value: 'Vulnerabilidad económica',
              align: 'left',
              bgColor: '#A6A6A6',
              textColor: '#000000',
              isBold: true,
            },
            {
              id: 'c2-2',
              value: 'Proporción del gasto de alimentos (% gastos)',
              align: 'left',
              bgColor: '#EBF1F5',
              textColor: '#1E293B',
            },
            {
              id: 'c2-3',
              value: '< 50%',
              align: 'center',
              badgeColor: 'green',
              bgColor: '#F2F8EC',
            },
            {
              id: 'c2-4',
              value: '50% - <65%',
              align: 'center',
              badgeColor: 'yellow',
              bgColor: '#FFFDE6',
            },
            {
              id: 'c2-5',
              value: '65% - <75%',
              align: 'center',
              badgeColor: 'orange',
              bgColor: '#FEF4EA',
            },
            {
              id: 'c2-6',
              value: '≥ 75%',
              align: 'center',
              badgeColor: 'red',
              bgColor: '#FDECEC',
            },
          ],
        },
        {
          id: 'cari-row-3',
          cells: [
            {
              id: 'c3-1',
              value: 'Agotamiento de activos',
              align: 'left',
              bgColor: '#B4C6E7',
              textColor: '#000000',
              isBold: true,
            },
            {
              id: 'c3-2',
              value: 'Estrategias de sobrevivencia - ES',
              align: 'left',
              bgColor: '#EBF1F5',
              textColor: '#1E293B',
            },
            {
              id: 'c3-3',
              value: 'Ninguna',
              align: 'center',
              badgeColor: 'green',
              bgColor: '#F2F8EC',
            },
            {
              id: 'c3-4',
              value: 'Estrategias de estrés',
              align: 'center',
              badgeColor: 'yellow',
              bgColor: '#FFFDE6',
            },
            {
              id: 'c3-5',
              value: 'Estrategias de crisis',
              align: 'center',
              badgeColor: 'orange',
              bgColor: '#FEF4EA',
            },
            {
              id: 'c3-6',
              value: 'Estrategias de emergencia',
              align: 'center',
              badgeColor: 'red',
              bgColor: '#FDECEC',
            },
          ],
        },
      ],
    },
  },
  {
    id: 'san-criterios-colores',
    name: '2. Criterios SAN Departamentales',
    description: 'Clasificación de fases de Seguridad Alimentaria y Nutricional (IPC/SAN) con bloques cromáticos corporativos.',
    category: 'Seguridad Alimentaria',
    data: {
      title: 'Monitoreo de Criterios SAN y Clasificación de Severidad',
      subtitle: 'Evaluación Periódica de Hogares Vulnerables - ACH Territorios',
      headers: ['Zona / Departamento', 'Población Evaluada', 'FCS (Consumo)', 'CSI (Afrontamiento)', 'Fase IPC Estimada', 'Acción Prioritaria'],
      notes: 'Fuente: Sistema de Alerta Temprana y Monitoreo Nutricional ACH. FCS: Food Consumption Score; CSI: Coping Strategy Index.',
      source: 'Equipo Técnico SAN - Acción contra el Hambre',
      suggestedChartType: 'bar',
      chartLabelCol: 0,
      chartValueCols: [1],
      highlightStyle: 'soft-pastel',
      rows: [
        {
          id: 'row-1',
          cells: [
            { id: 'c1-1', value: 'Guajira Alta - Zona Rural', align: 'left', badgeColor: 'none' },
            { id: 'c1-2', value: '4,280', align: 'right', badgeColor: 'none' },
            { id: 'c1-3', value: 'Pobre (38.5%)', align: 'center', badgeColor: 'orange' },
            { id: 'c1-4', value: 'Severo (>19)', align: 'center', badgeColor: 'orange' },
            { id: 'c1-5', value: 'Fase 3: Crisis', align: 'center', badgeColor: 'orange' },
            { id: 'c1-6', value: 'Distribución de Alimentos y Agua', align: 'left', badgeColor: 'none' },
          ],
        },
        {
          id: 'row-2',
          cells: [
            { id: 'c2-1', value: 'Guajira Media - Asentamientos', align: 'left', badgeColor: 'none' },
            { id: 'c2-2', value: '6,150', align: 'right', badgeColor: 'none' },
            { id: 'c2-3', value: 'Límite (29.2%)', align: 'center', badgeColor: 'blue' },
            { id: 'c2-4', value: 'Moderado (10-18)', align: 'center', badgeColor: 'blue' },
            { id: 'c2-5', value: 'Fase 2: Estrés', align: 'center', badgeColor: 'blue' },
            { id: 'c2-6', value: 'Transferencias Monetarias Multiproceso', align: 'left', badgeColor: 'none' },
          ],
        },
        {
          id: 'row-3',
          cells: [
            { id: 'c3-1', value: 'Chocó - Cuenca del Río San Juan', align: 'left', badgeColor: 'none' },
            { id: 'c3-2', value: '3,890', align: 'right', badgeColor: 'none' },
            { id: 'c3-3', value: 'Pobre (44.1%)', align: 'center', badgeColor: 'orange' },
            { id: 'c3-4', value: 'Crítico (>25)', align: 'center', badgeColor: 'orange' },
            { id: 'c3-5', value: 'Fase 4: Emergencia', align: 'center', badgeColor: 'orange' },
            { id: 'c3-6', value: 'Despliegue Brigada Médica-Nutricional', align: 'left', badgeColor: 'none' },
          ],
        },
        {
          id: 'row-4',
          cells: [
            { id: 'c4-1', value: 'Nariño - Costa Pacífica', align: 'left', badgeColor: 'none' },
            { id: 'c4-2', value: '5,420', align: 'right', badgeColor: 'none' },
            { id: 'c4-3', value: 'Aceptable (62.0%)', align: 'center', badgeColor: 'green' },
            { id: 'c4-4', value: 'Bajo (0-9)', align: 'center', badgeColor: 'green' },
            { id: 'c4-5', value: 'Fase 1: Mínima', align: 'center', badgeColor: 'green' },
            { id: 'c4-6', value: 'Fortalecimiento de Medios de Vida', align: 'left', badgeColor: 'none' },
          ],
        },
        {
          id: 'row-5',
          cells: [
            { id: 'c5-1', value: 'Arauca - Frontera', align: 'left', badgeColor: 'none' },
            { id: 'c5-2', value: '4,960', align: 'right', badgeColor: 'none' },
            { id: 'c5-3', value: 'Límite (33.4%)', align: 'center', badgeColor: 'blue' },
            { id: 'c5-4', value: 'Moderado (11-17)', align: 'center', badgeColor: 'blue' },
            { id: 'c5-5', value: 'Fase 2: Estrés', align: 'center', badgeColor: 'blue' },
            { id: 'c5-6', value: 'Apoyo a Huertos Comunitarios y WASH', align: 'left', badgeColor: 'none' },
          ],
        },
        {
          id: 'row-6',
          cells: [
            { id: 'c6-1', value: 'Total / Promedio General', align: 'left', badgeColor: 'gray' },
            { id: 'c6-2', value: '24,700', align: 'right', badgeColor: 'gray' },
            { id: 'c6-3', value: '35.4% Vulnerables', align: 'center', badgeColor: 'gray' },
            { id: 'c6-4', value: 'CSI Prom: 16.2', align: 'center', badgeColor: 'gray' },
            { id: 'c6-5', value: 'Fase 2 Global', align: 'center', badgeColor: 'gray' },
            { id: 'c6-6', value: 'Respuesta Integral Multisectorial', align: 'left', badgeColor: 'gray' },
          ],
        },
      ],
    },
  },
  {
    id: 'desglose-geografico-rowspan',
    name: '2. Desglose Geográfico por Países y Municipios (Rowspan)',
    description: 'Estructura multinivel con celdas agrupadas por país y departamento/municipio, metas y coberturas.',
    category: 'Operaciones de Campo',
    data: {
      title: 'Desglose Territorial de Beneficiarios por País y Municipio',
      subtitle: 'Programa Regional de Emergencia y Resiliencia Humanitaria ACH 2024-2025',
      headers: ['País', 'Departamento / Región', 'Municipio Focalizado', 'Meta Proyectada', 'Alcanzados', '% Cumplimiento'],
      notes: 'Los países y departamentos agrupan las intervenciones activas con financiamiento humanitario.',
      source: 'Dirección de Operaciones y M&E - Acción contra el Hambre',
      suggestedChartType: 'horizontalBar',
      chartLabelCol: 2,
      chartValueCols: [3, 4],
      rows: [
        {
          id: 'geo-1',
          cells: [
            { id: 'g1-1', value: 'Colombia', align: 'center', badgeColor: 'blue', rowSpan: 3 },
            { id: 'g1-2', value: 'La Guajira', align: 'left', badgeColor: 'none' },
            { id: 'g1-3', value: 'Uribia', align: 'left', badgeColor: 'none' },
            { id: 'g1-4', value: '5,000', align: 'right', badgeColor: 'none' },
            { id: 'g1-5', value: '5,240', align: 'right', badgeColor: 'none' },
            { id: 'g1-6', value: '105%', align: 'center', badgeColor: 'green' },
          ],
        },
        {
          id: 'geo-2',
          cells: [
            { id: 'g2-2', value: 'La Guajira', align: 'left', badgeColor: 'none' },
            { id: 'g2-3', value: 'Manaure', align: 'left', badgeColor: 'none' },
            { id: 'g2-4', value: '4,200', align: 'right', badgeColor: 'none' },
            { id: 'g2-5', value: '4,050', align: 'right', badgeColor: 'none' },
            { id: 'g2-6', value: '96%', align: 'center', badgeColor: 'green' },
          ],
        },
        {
          id: 'geo-3',
          cells: [
            { id: 'g3-2', value: 'Nariño', align: 'left', badgeColor: 'none' },
            { id: 'g3-3', value: 'Tumaco', align: 'left', badgeColor: 'none' },
            { id: 'g3-4', value: '3,800', align: 'right', badgeColor: 'none' },
            { id: 'g3-5', value: '3,150', align: 'right', badgeColor: 'none' },
            { id: 'g3-6', value: '83%', align: 'center', badgeColor: 'blue' },
          ],
        },
        {
          id: 'geo-4',
          cells: [
            { id: 'g4-1', value: 'Guatemala', align: 'center', badgeColor: 'blue', rowSpan: 2 },
            { id: 'g4-2', value: 'Chiquimula (Corredor Seco)', align: 'left', badgeColor: 'none' },
            { id: 'g4-3', value: 'Jocotán', align: 'left', badgeColor: 'none' },
            { id: 'g4-4', value: '3,500', align: 'right', badgeColor: 'none' },
            { id: 'g4-5', value: '3,620', align: 'right', badgeColor: 'none' },
            { id: 'g4-6', value: '103%', align: 'center', badgeColor: 'green' },
          ],
        },
        {
          id: 'geo-5',
          cells: [
            { id: 'g5-2', value: 'Chiquimula (Corredor Seco)', align: 'left', badgeColor: 'none' },
            { id: 'g5-3', value: 'Camotán', align: 'left', badgeColor: 'none' },
            { id: 'g5-4', value: '2,900', align: 'right', badgeColor: 'none' },
            { id: 'g5-5', value: '2,250', align: 'right', badgeColor: 'none' },
            { id: 'g5-6', value: '78%', align: 'center', badgeColor: 'orange' },
          ],
        },
        {
          id: 'geo-6',
          cells: [
            { id: 'g6-1', value: 'Haití', align: 'center', badgeColor: 'blue', rowSpan: 2 },
            { id: 'g6-2', value: 'Noroeste', align: 'left', badgeColor: 'none' },
            { id: 'g6-3', value: 'Port-de-Paix', align: 'left', badgeColor: 'none' },
            { id: 'g6-4', value: '6,000', align: 'right', badgeColor: 'none' },
            { id: 'g6-5', value: '5,820', align: 'right', badgeColor: 'none' },
            { id: 'g6-6', value: '97%', align: 'center', badgeColor: 'green' },
          ],
        },
        {
          id: 'geo-7',
          cells: [
            { id: 'g7-2', value: 'Artibonite', align: 'left', badgeColor: 'none' },
            { id: 'g7-3', value: 'Gonaïves', align: 'left', badgeColor: 'none' },
            { id: 'g7-4', value: '4,500', align: 'right', badgeColor: 'none' },
            { id: 'g7-5', value: '3,400', align: 'right', badgeColor: 'none' },
            { id: 'g7-6', value: '76%', align: 'center', badgeColor: 'orange' },
          ],
        },
      ],
    },
  },
  {
    id: 'porcentajes-san-barras',
    name: '3. Porcentajes SAN en Barras Embebidas',
    description: 'Tabla con mini-barras horizontales visuales incrustadas en las celdas para indicadores porcentuales.',
    category: 'Monitoreo e Indicadores',
    data: {
      title: 'Estado de Indicadores Clave de Seguridad Nutricional y WASH',
      subtitle: 'Seguimiento Mensual de Cobertura en Comunidades de Atención Prioritaria',
      headers: ['Indicador Humanitario', 'Línea de Base', 'Meta Operativa', 'Progreso Actual (%)', 'Barra Visual ACH', 'Estado de Avance'],
      notes: 'Las barras representan el porcentaje relativo hacia el cumplimiento de la meta humanitaria.',
      source: 'Panel de Rendición de Cuentas ACH',
      suggestedChartType: 'bar',
      chartLabelCol: 0,
      chartValueCols: [3],
      rows: [
        {
          id: 'pb-1',
          cells: [
            { id: 'pb1-1', value: 'Acceso a Agua Segura (L/persona/día >= 15L)', align: 'left', badgeColor: 'none' },
            { id: 'pb1-2', value: '25%', align: 'center', badgeColor: 'none' },
            { id: 'pb1-3', value: '85%', align: 'center', badgeColor: 'none' },
            { id: 'pb1-4', value: '92%', align: 'right', badgeColor: 'green' },
            { id: 'pb1-5', value: '92%', align: 'left', badgeColor: 'green', isProgressBar: true, progressPercent: 92 },
            { id: 'pb1-6', value: 'Excelente', align: 'center', badgeColor: 'green' },
          ],
        },
        {
          id: 'pb-2',
          cells: [
            { id: 'pb2-1', value: 'Niños/as con Desnutrición Aguda en Tratamiento (OTP)', align: 'left', badgeColor: 'none' },
            { id: 'pb2-2', value: '18%', align: 'center', badgeColor: 'none' },
            { id: 'pb2-3', value: '90%', align: 'center', badgeColor: 'none' },
            { id: 'pb2-4', value: '84%', align: 'right', badgeColor: 'blue' },
            { id: 'pb2-5', value: '84%', align: 'left', badgeColor: 'blue', isProgressBar: true, progressPercent: 84 },
            { id: 'pb2-6', value: 'En Meta', align: 'center', badgeColor: 'blue' },
          ],
        },
        {
          id: 'pb-3',
          cells: [
            { id: 'pb3-1', value: 'Madres en Asesoría de Lactancia y Alimentación Complementaria', align: 'left', badgeColor: 'none' },
            { id: 'pb3-2', value: '30%', align: 'center', badgeColor: 'none' },
            { id: 'pb3-3', value: '80%', align: 'center', badgeColor: 'none' },
            { id: 'pb3-4', value: '68%', align: 'right', badgeColor: 'orange' },
            { id: 'pb3-5', value: '68%', align: 'left', badgeColor: 'orange', isProgressBar: true, progressPercent: 68 },
            { id: 'pb3-6', value: 'Atención Requerida', align: 'center', badgeColor: 'orange' },
          ],
        },
        {
          id: 'pb-4',
          cells: [
            { id: 'pb4-1', value: 'Hogares con Filtros y Almacenamiento Seguro de Agua', align: 'left', badgeColor: 'none' },
            { id: 'pb4-2', value: '12%', align: 'center', badgeColor: 'none' },
            { id: 'pb4-3', value: '75%', align: 'center', badgeColor: 'none' },
            { id: 'pb4-4', value: '78%', align: 'right', badgeColor: 'green' },
            { id: 'pb4-5', value: '78%', align: 'left', badgeColor: 'green', isProgressBar: true, progressPercent: 78 },
            { id: 'pb4-6', value: 'Satisfactorio', align: 'center', badgeColor: 'green' },
          ],
        },
        {
          id: 'pb-5',
          cells: [
            { id: 'pb5-1', value: 'Diversificación Productiva en Huertos Familiares', align: 'left', badgeColor: 'none' },
            { id: 'pb5-2', value: '15%', align: 'center', badgeColor: 'none' },
            { id: 'pb5-3', value: '70%', align: 'center', badgeColor: 'none' },
            { id: 'pb5-4', value: '54%', align: 'right', badgeColor: 'orange' },
            { id: 'pb5-5', value: '54%', align: 'left', badgeColor: 'orange', isProgressBar: true, progressPercent: 54 },
            { id: 'pb5-6', value: 'Retraso Moderado', align: 'center', badgeColor: 'orange' },
          ],
        },
        {
          id: 'pb-6',
          cells: [
            { id: 'pb6-1', value: 'Entrega Oportuna de Transferencias Monetarias (CVA)', align: 'left', badgeColor: 'none' },
            { id: 'pb6-2', value: '0%', align: 'center', badgeColor: 'none' },
            { id: 'pb6-3', value: '100%', align: 'center', badgeColor: 'none' },
            { id: 'pb6-4', value: '98%', align: 'right', badgeColor: 'green' },
            { id: 'pb6-5', value: '98%', align: 'left', badgeColor: 'green', isProgressBar: true, progressPercent: 98 },
            { id: 'pb6-6', value: 'Cumplido', align: 'center', badgeColor: 'green' },
          ],
        },
      ],
    },
  },
  {
    id: 'presupuesto-fondos-sectores',
    name: '4. Presupuesto y Ejecución por Sectores Técnicos',
    description: 'Distribución financiera por clúster (Nutrición, WASH, Salud, Medios de Vida) y donante.',
    category: 'Financiero y Fondos',
    data: {
      title: 'Ejecución Presupuestaria por Sector Humanitario ACH',
      subtitle: 'Consolidado Anual de Fondos (ECHO, USAID/BHA, AECID, Fondos Propios)',
      headers: ['Sector Técnico ACH', 'Presupuesto Asignado (EUR)', 'Gasto Ejecutado (EUR)', '% Ejecución', 'Donante Principal', 'Estado'],
      notes: 'Cifras expresadas en Euros (€) según contabilidad oficial ACH.',
      source: 'Departamento Financiero y de Control de Gestión ACH',
      suggestedChartType: 'pie',
      chartLabelCol: 0,
      chartValueCols: [2],
      rows: [
        {
          id: 'f-1',
          cells: [
            { id: 'f1-1', value: 'Nutrición y Salud Comunitaria', align: 'left', badgeColor: 'none' },
            { id: 'f1-2', value: '1,450,000 €', align: 'right', badgeColor: 'none' },
            { id: 'f1-3', value: '1,320,000 €', align: 'right', badgeColor: 'none' },
            { id: 'f1-4', value: '91%', align: 'center', badgeColor: 'green' },
            { id: 'f1-5', value: 'ECHO / UE', align: 'left', badgeColor: 'none' },
            { id: 'f1-6', value: 'En tiempo', align: 'center', badgeColor: 'green' },
          ],
        },
        {
          id: 'f-2',
          cells: [
            { id: 'f2-1', value: 'Agua, Saneamiento e Higiene (WASH)', align: 'left', badgeColor: 'none' },
            { id: 'f2-2', value: '1,180,000 €', align: 'right', badgeColor: 'none' },
            { id: 'f2-3', value: '1,050,000 €', align: 'right', badgeColor: 'none' },
            { id: 'f2-4', value: '89%', align: 'center', badgeColor: 'blue' },
            { id: 'f2-5', value: 'USAID / BHA', align: 'left', badgeColor: 'none' },
            { id: 'f2-6', value: 'En tiempo', align: 'center', badgeColor: 'green' },
          ],
        },
        {
          id: 'f-3',
          cells: [
            { id: 'f3-1', value: 'Seguridad Alimentaria y Medios de Vida', align: 'left', badgeColor: 'none' },
            { id: 'f3-2', value: '980,000 €', align: 'right', badgeColor: 'none' },
            { id: 'f3-3', value: '820,000 €', align: 'right', badgeColor: 'none' },
            { id: 'f3-4', value: '84%', align: 'center', badgeColor: 'blue' },
            { id: 'f3-5', value: 'AECID', align: 'left', badgeColor: 'none' },
            { id: 'f3-6', value: 'Revisión técnica', align: 'center', badgeColor: 'blue' },
          ],
        },
        {
          id: 'f-4',
          cells: [
            { id: 'f4-1', value: 'Transferencias Monetarias Multiproceso (CVA)', align: 'left', badgeColor: 'none' },
            { id: 'f4-2', value: '750,000 €', align: 'right', badgeColor: 'none' },
            { id: 'f4-3', value: '710,000 €', align: 'right', badgeColor: 'none' },
            { id: 'f4-4', value: '95%', align: 'center', badgeColor: 'green' },
            { id: 'f4-5', value: 'Fondos Propios ACH', align: 'left', badgeColor: 'none' },
            { id: 'f4-6', value: 'Cierre próximo', align: 'center', badgeColor: 'green' },
          ],
        },
        {
          id: 'f-5',
          cells: [
            { id: 'f5-1', value: 'Protección y Enfoque de Género Transversal', align: 'left', badgeColor: 'none' },
            { id: 'f5-2', value: '340,000 €', align: 'right', badgeColor: 'none' },
            { id: 'f5-3', value: '255,000 €', align: 'right', badgeColor: 'none' },
            { id: 'f5-4', value: '75%', align: 'center', badgeColor: 'orange' },
            { id: 'f5-5', value: 'ACNUR / UNICEF', align: 'left', badgeColor: 'none' },
            { id: 'f5-6', value: 'Aceleración requerida', align: 'center', badgeColor: 'orange' },
          ],
        },
        {
          id: 'f-6',
          cells: [
            { id: 'f6-1', value: 'Total Consolidado', align: 'left', badgeColor: 'gray' },
            { id: 'f6-2', value: '4,700,000 €', align: 'right', badgeColor: 'gray' },
            { id: 'f6-3', value: '4,155,000 €', align: 'right', badgeColor: 'gray' },
            { id: 'f6-4', value: '88.4%', align: 'center', badgeColor: 'gray' },
            { id: 'f6-5', value: 'Múltiples Donantes', align: 'left', badgeColor: 'gray' },
            { id: 'f6-6', value: 'Ejecución Saludable', align: 'center', badgeColor: 'gray' },
          ],
        },
      ],
    },
  },
];
